name: oref_examples
description: "Oref examples app"
publish_to: "none"

version: 1.0.0+1

resolution: workspace
environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  oref: any

flutter:
  uses-material-design: true
