name: oref
description: A high-performance Flutter state management tool, Oref is one of the fastest Flutter signals and state management solutions.

version: 2.6.0
repository: https://github.com/medz/oref

topics:
  - signals
  - reactive
  - state-management
  - alien-signals

funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

workspace:
  - example

dependencies:
  flutter:
    sdk: flutter
  alien_signals: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
