name: oref
description: A reactive state management library for Flutter that adds magic to any Widget with signals, computed values, and effects powered by alien_signals.
version: 2.3.1
repository: https://github.com/medz/oref

topics:
  - signals
  - reactive
  - state-management
  - alien-signals

funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

workspace:
  - example

dependencies:
  flutter:
    sdk: flutter
  alien_signals: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
