name: oref_analyzer_tests
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  analyzer: ^10.0.1
  analyzer_testing: ^0.1.9
  oref:
    path: ..
  test: ^1.26.1
  test_reflective_loader: ^0.4.0

dev_dependencies:
  lints: ^6.0.0
